---
- name: configure and deploy the webservers
  hosts: webservers
  remote_user: root
  roles:
    - web

- name: configure and deploy the dbservers
  hosts: dbservers
  remote_user: root
  roles:
    - db

- name: configure and deploy the appservers
  hosts: appservers
  remote_user: root
  roles:
    - app
